### ISSUE TITLE
Add ELB/ALB/NLB

### ISSUE THREAD

**Issue by aws-u** [AwsGeek/aws-history#9]
Kindly add ELB releases! ELB is 10 years old! It's very special!

**Comment by colmmacc** [comment]
https://aws.amazon.com/blogs/aws/new-aws-load-balancing-automatic-scaling-and-cloud-monitoring-services/

18 May 2009 - ELB (now CLB), CloudWatch, AutoScaling. 
 11 August 2016 - https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

**Comment by AwsGeek** [comment]
Added ELB
